"""Non-attribution scrubbing for commits and text artefacts (EXG-INV-03)."""

from __future__ import annotations

import re
import subprocess  # nosec B404 - fixed git argv for commit rewrite.
import sys
from pathlib import Path

ATTRIBUTION_LINE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^Co-Authored-By:\s*.+$", re.IGNORECASE | re.MULTILINE),
    re.compile(r"^Generated-with:\s*.+$", re.IGNORECASE | re.MULTILINE),
    re.compile(r"^Generated-by:\s*.+$", re.IGNORECASE | re.MULTILINE),
    re.compile(r"^Assisted-by:\s*.+$", re.IGNORECASE | re.MULTILINE),
)

ATTRIBUTION_CONTENT_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"Co-Authored-By:\s*.+", re.IGNORECASE),
    re.compile(r"Generated with (?:Cursor|Claude|Codex|ChatGPT|Copilot)", re.IGNORECASE),
    re.compile(r"Generated by (?:Cursor|Claude|Codex|ChatGPT|Copilot)", re.IGNORECASE),
    re.compile(
        r"\b(?:Cursor|Claude Code|OpenAI Codex|GitHub Copilot)\b"
        r".*\b(?:authored|generated|assisted)\b",
        re.IGNORECASE,
    ),
)


def scrub_commit_message(message: str) -> str:
    """Remove IA attribution trailers from a commit message.

    :param message: Original commit message body.
    :returns: Scrubbed message with trailing attribution lines removed.
    """
    cleaned = message
    for pattern in ATTRIBUTION_LINE_PATTERNS:
        cleaned = pattern.sub("", cleaned)
    lines = [line.rstrip() for line in cleaned.splitlines()]
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines) + ("\n" if lines else "")


def scan_text_for_attribution(text: str) -> tuple[str, ...]:
    """Return human-readable matches when attribution motifs appear in ``text``.

    :param text: Text to scan (commit message, PR body, doc fragment).
    :returns: Unique match descriptions suitable for gate motifs.
    """
    matches: list[str] = []
    for pattern in ATTRIBUTION_CONTENT_PATTERNS:
        for found in pattern.findall(text):
            snippet = found if isinstance(found, str) else found[0]
            normalized = " ".join(snippet.split())
            if normalized not in matches:
                matches.append(normalized)
    return tuple(matches)


def rewrite_commits_since(workdir: Path, baseline_ref: str) -> tuple[str, ...]:
    """Rewrite commit messages between ``baseline_ref`` and ``HEAD`` when needed.

    :param workdir: Git worktree containing the commits.
    :param baseline_ref: Baseline ref excluding history to preserve.
    :returns: Commit hashes whose messages were rewritten.
    :raises subprocess.CalledProcessError: If git commands fail unexpectedly.
    """
    resolved = workdir.resolve()
    commits = _commits_since(resolved, baseline_ref)
    to_rewrite = [
        commit for commit in commits if scan_text_for_attribution(_commit_message(resolved, commit))
    ]
    if not to_rewrite:
        return ()

    filter_script = (
        f'"{sys.executable}" -c "from src.policy.attribution_scrubber import '
        'scrub_stdin; scrub_stdin()"'
    )
    subprocess.run(  # nosec B603 B607
        [
            "git",
            "filter-branch",
            "-f",
            "--msg-filter",
            filter_script,
            f"{baseline_ref}..HEAD",
        ],
        cwd=resolved,
        check=True,
        capture_output=True,
    )
    return tuple(to_rewrite)


def scrub_stdin() -> None:
    """Entry point for ``git filter-branch --msg-filter``."""
    sys.stdout.write(scrub_commit_message(sys.stdin.read()))


def _commits_since(workdir: Path, baseline_ref: str) -> tuple[str, ...]:
    result = subprocess.run(  # nosec B603 B607
        ["git", "rev-list", "--reverse", f"{baseline_ref}..HEAD"],
        cwd=workdir,
        check=True,
        capture_output=True,
        text=True,
    )
    return tuple(line.strip() for line in result.stdout.splitlines() if line.strip())


def _commit_message(workdir: Path, commit_hash: str) -> str:
    result = subprocess.run(  # nosec B603 B607
        ["git", "show", "-s", "--format=%B", commit_hash],
        cwd=workdir,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout
